# Generated by Django 4.0.4 on 2022-05-11 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0003_remove_categoria_comentario'),
        ('posts', '0002_alter_post_autor_post_alter_post_conteudo_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categorias_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categorias.categoria', verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo_post',
            field=models.CharField(max_length=255, verbose_name='Titulo'),
        ),
    ]
