# Generated by Django 4.0.4 on 2022-05-10 14:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='comentario',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
