# Generated by Django 4.0.4 on 2022-05-10 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_categoria_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='comentario',
        ),
    ]
